-- Fuel entries table
CREATE TABLE fuel_entries (
  id SERIAL PRIMARY KEY,
  vehicle_id INTEGER NOT NULL REFERENCES vehicles(id) ON DELETE CASCADE,
  station_id INTEGER REFERENCES fuel_stations(id) ON DELETE SET NULL,
  mileage_km INTEGER NOT NULL,
  litres DOUBLE PRECISION NOT NULL,
  cost DOUBLE PRECISION NOT NULL,
  filled_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
